// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA8QwOpUbwTJCn_j9rc8ndot6LYyH44TM',
    appId: '1:204986415138:web:11c1688ba573943712327b',
    messagingSenderId: '204986415138',
    projectId: 'taller-3-4fca0',
    authDomain: 'taller-3-4fca0.firebaseapp.com',
    databaseURL: 'https://taller-3-4fca0-default-rtdb.firebaseio.com',
    storageBucket: 'taller-3-4fca0.firebasestorage.app',
    measurementId: 'G-HK0LCRVGJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Wq8wiFUx1LSNkH6BlZAqzxnpiEdFBU8',
    appId: '1:204986415138:android:b46c801774d834ed12327b',
    messagingSenderId: '204986415138',
    projectId: 'taller-3-4fca0',
    databaseURL: 'https://taller-3-4fca0-default-rtdb.firebaseio.com',
    storageBucket: 'taller-3-4fca0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC61bLwOXnHhQOrOkyF-wUOTkSS9Vq6eTU',
    appId: '1:204986415138:ios:bae67cbf93e6c6ef12327b',
    messagingSenderId: '204986415138',
    projectId: 'taller-3-4fca0',
    databaseURL: 'https://taller-3-4fca0-default-rtdb.firebaseio.com',
    storageBucket: 'taller-3-4fca0.firebasestorage.app',
    iosBundleId: 'com.example.flutterimc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC61bLwOXnHhQOrOkyF-wUOTkSS9Vq6eTU',
    appId: '1:204986415138:ios:bae67cbf93e6c6ef12327b',
    messagingSenderId: '204986415138',
    projectId: 'taller-3-4fca0',
    databaseURL: 'https://taller-3-4fca0-default-rtdb.firebaseio.com',
    storageBucket: 'taller-3-4fca0.firebasestorage.app',
    iosBundleId: 'com.example.flutterimc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA8QwOpUbwTJCn_j9rc8ndot6LYyH44TM',
    appId: '1:204986415138:web:f9906b3392e8431612327b',
    messagingSenderId: '204986415138',
    projectId: 'taller-3-4fca0',
    authDomain: 'taller-3-4fca0.firebaseapp.com',
    databaseURL: 'https://taller-3-4fca0-default-rtdb.firebaseio.com',
    storageBucket: 'taller-3-4fca0.firebasestorage.app',
    measurementId: 'G-SH41TQJ6VT',
  );
}
